package forms;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import domain.Bibliotekar;
import java.awt.Color;
import javax.swing.JOptionPane;
import table.BibliotekarTableModel;
import threads.ServerThread;

/**
 *
 * @author Korisnik
 */
public class ServerForm extends javax.swing.JFrame {

    private ServerThread serverThread;
    private BibliotekarTableModel tableModel;

    /**
     * Creates new form ServerFrm
     */
    public ServerForm() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartServer = new javax.swing.JButton();
        btnStopServer = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Серверска форма");

        btnStartServer.setBackground(java.awt.Color.green);
        btnStartServer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStartServer.setText("Покрени");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        btnStopServer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStopServer.setText("Заустави");
        btnStopServer.setEnabled(false);
        btnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopServerActionPerformed(evt);
            }
        });

        lblStatus.setForeground(java.awt.Color.red);
        lblStatus.setText("заустављен");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Улоговани админи:");

        jLabel2.setText("Статус сервера:");

        jMenuBar.setMinimumSize(getMaximumSize());

        jMenu.setText("Подешавања");
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuMousePressed(evt);
            }
        });
        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(btnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartServer)
                    .addComponent(btnStopServer))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblStatus))
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
            serverThread = new ServerThread(this);
            serverThread.start();
            btnStartServer.setEnabled(false);
            btnStopServer.setEnabled(true);
            btnStartServer.setBackground(Color.white);
            btnStopServer.setBackground(Color.red);
            lblStatus.setText("покренут");
            lblStatus.setForeground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Сервер је покренут.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Неуспешно покретање сервера:\n" + ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopServerActionPerformed
        try {
            serverThread.stopServer();
            serverThread = null;
            btnStartServer.setEnabled(true);
            btnStopServer.setEnabled(false);
            btnStartServer.setBackground(Color.green);
            btnStopServer.setBackground(Color.white);
            lblStatus.setText("заустављен");
            lblStatus.setForeground(Color.RED);
            tableModel.clear();
            JOptionPane.showMessageDialog(this, "Сервер је заустављен.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Неуспешно заустављање сервера:\n" + ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStopServerActionPerformed

    private void jMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMousePressed
        openDbSettingsForm();
    }//GEN-LAST:event_jMenuMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        prepareTable();
    }

    private void prepareTable() {
        tableModel = new BibliotekarTableModel();
        tbl.setModel(tableModel);
    }

    public void addBibliotekarToTable(Bibliotekar bibliotekar) {
        tableModel.addBibliotekar(bibliotekar);
    }

    public void removeBibliotekarFromTable(Bibliotekar bibliotekar) {
        tableModel.removeBibliotekar(bibliotekar);
    }

    public void openDbSettingsForm() {
        new DbSettingsForm(this, true, false).setVisible(true);
    }
}
