/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dialogs.ChangeLoanRecordForm;
import dialogs.ChangeMemberForm;
import dialogs.CreateShiftForm;
import dialogs.ViewLoanRecordsForm;
import dialogs.ViewMembersForm;
import domain.Bibliotekar;

/**
 *
 * @author Korisnik
 */
public class MainForm extends javax.swing.JFrame {

    private Bibliotekar logged;

    /**
     * Creates new form MainForm
     */
   public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MainForm(Bibliotekar logged) {
        this();
        this.logged = logged;
        txtUsername.setEditable(false);
        if (logged != null) {
            txtUsername.setText(logged.getKorisnickoIme());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLoanRecords = new javax.swing.JMenu();
        jMenuItemCreateLoadRecord = new javax.swing.JMenuItem();
        jMenuViewLoanRecords = new javax.swing.JMenuItem();
        jMenuMembers = new javax.swing.JMenu();
        jMenuItemCreateMember = new javax.swing.JMenuItem();
        jMenuItemViewMembers = new javax.swing.JMenuItem();
        jMenuShifts = new javax.swing.JMenu();
        jMenuItemCreateShift = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Главна форма");

        jLabel1.setText("Добродошли:");

        jLabel2.setText("Систем за евиденцију позајмица у библиотеци");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jMenuLoanRecords.setText("Евиденције");

        jMenuItemCreateLoadRecord.setText("Додај нову евиденцију");
        jMenuItemCreateLoadRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateLoadRecordActionPerformed(evt);
            }
        });
        jMenuLoanRecords.add(jMenuItemCreateLoadRecord);

        jMenuViewLoanRecords.setText("Прегледај евиденције ");
        jMenuViewLoanRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuViewLoanRecordsActionPerformed(evt);
            }
        });
        jMenuLoanRecords.add(jMenuViewLoanRecords);

        jMenuBar1.add(jMenuLoanRecords);

        jMenuMembers.setText("Чланови");

        jMenuItemCreateMember.setText("Додај новог члана");
        jMenuItemCreateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateMemberActionPerformed(evt);
            }
        });
        jMenuMembers.add(jMenuItemCreateMember);

        jMenuItemViewMembers.setText("Прегледај чланове");
        jMenuItemViewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewMembersActionPerformed(evt);
            }
        });
        jMenuMembers.add(jMenuItemViewMembers);

        jMenuBar1.add(jMenuMembers);

        jMenuShifts.setText("Смене");

        jMenuItemCreateShift.setText("Креирај нову смену");
        jMenuItemCreateShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateShiftActionPerformed(evt);
            }
        });
        jMenuShifts.add(jMenuItemCreateShift);

        jMenuBar1.add(jMenuShifts);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addComponent(jLabel2))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateLoadRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateLoadRecordActionPerformed
        new ChangeLoanRecordForm(this, true, logged, null).setVisible(true);
    }//GEN-LAST:event_jMenuItemCreateLoadRecordActionPerformed

    private void jMenuViewLoanRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuViewLoanRecordsActionPerformed
        new ViewLoanRecordsForm(this, true, logged).setVisible(true);
    }//GEN-LAST:event_jMenuViewLoanRecordsActionPerformed

    private void jMenuItemCreateShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateShiftActionPerformed
        new CreateShiftForm(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemCreateShiftActionPerformed

    private void jMenuItemCreateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateMemberActionPerformed
        new ChangeMemberForm(this, true, null).setVisible(true);
    }//GEN-LAST:event_jMenuItemCreateMemberActionPerformed

    private void jMenuItemViewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewMembersActionPerformed
        new ViewMembersForm(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemViewMembersActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        
    }//GEN-LAST:event_txtUsernameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCreateLoadRecord;
    private javax.swing.JMenuItem jMenuItemCreateMember;
    private javax.swing.JMenuItem jMenuItemCreateShift;
    private javax.swing.JMenuItem jMenuItemViewMembers;
    private javax.swing.JMenu jMenuLoanRecords;
    private javax.swing.JMenu jMenuMembers;
    private javax.swing.JMenu jMenuShifts;
    private javax.swing.JMenuItem jMenuViewLoanRecords;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
