/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogs;

import controller.ClientController;
import domain.Bibliotekar;
import domain.Clan;
import domain.EvidencijaPozajmice;
import domain.Knjiga;
import domain.State;
import domain.StavkaPozajmice;
import exceptions.ClientValidationException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import table.StavkaPozajmiceTableModel;
import util.Utility;

/**
 *
 * @author Korisnik
 */
public class ChangeLoanRecordForm extends javax.swing.JDialog {

    private final Bibliotekar logged;
    private final EvidencijaPozajmice original;
    private final StavkaPozajmiceTableModel tableModel = new StavkaPozajmiceTableModel();

    /**
     * Creates new form ChangeLoanRecordForm
     */
    public ChangeLoanRecordForm(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null);
    }

    public ChangeLoanRecordForm(java.awt.Frame parent, boolean modal, Bibliotekar logged, EvidencijaPozajmice original) {
        super(parent, modal);
        this.logged = logged;
        this.original = original;
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbMember = new javax.swing.JComboBox();
        panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbBook = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtFinePerDay = new javax.swing.JTextField();
        txtDeadline = new javax.swing.JTextField();
        btnCreateItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoanItems = new javax.swing.JTable();
        btnSaveChanges = new javax.swing.JButton();
        btnCreateLoanRecord = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Датум изнајмљивања (дд.мм.гггг):");

        jLabel2.setText("Члан:");

        cmbMember.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Додај изнајмљене ставке"));

        jLabel5.setText("Рок за враћање (дд.мм.гггг):");

        jLabel3.setText("Књига:");

        cmbBook.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Цена казне по дану кашњења:");

        btnCreateItem.setText("Додај ставку евиденције");
        btnCreateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBook, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeadline))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnCreateItem)
                .addGap(57, 57, 57))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateItem))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFinePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblLoanItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLoanItems);

        btnSaveChanges.setText("Запамти измене");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnCreateLoanRecord.setText("Креирај евиденцију");
        btnCreateLoanRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLoanRecordActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Обриши ставку");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteItem)
                        .addGap(135, 135, 135)
                        .addComponent(btnCreateLoanRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveChanges)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbMember, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateLoanRecord)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnDeleteItem))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateItemActionPerformed
        addItem();
    }//GEN-LAST:event_btnCreateItemActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        saveChanges();
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnCreateLoanRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLoanRecordActionPerformed
        createLoanRecord();
    }//GEN-LAST:event_btnCreateLoanRecordActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        deleteItem();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateItem;
    private javax.swing.JButton btnCreateLoanRecord;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox cmbBook;
    private javax.swing.JComboBox cmbMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblLoanItems;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextField txtFinePerDay;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        setLocationRelativeTo(getParent());
        setTitle(original == null ? "Креирај евиденцију позајмице" : "Промени евиденцију позајмице");
        txtDate.setEditable(false);
        tblLoanItems.setModel(tableModel);

        loadComboData();

        if (original == null) {
            txtDate.setText(Utility.DATE_FORMAT.format(new Date()));
            txtFinePerDay.setText("10");
            txtDeadline.setText(Utility.DATE_FORMAT.format(getDefaultDeadline()));
            tableModel.setData(new ArrayList<>());
            btnCreateLoanRecord.setVisible(true);
            btnSaveChanges.setVisible(false);
        } else {
            txtDate.setText(Utility.DATE_FORMAT.format(original.getDatumIznajmljivanja()));
            txtFinePerDay.setText("10");
            txtDeadline.setText(Utility.DATE_FORMAT.format(getDefaultDeadline()));
            cmbMember.setSelectedItem(original.getClan());
            tableModel.setData(new ArrayList<>(original.getStavkePozajmice()));
            btnCreateLoanRecord.setVisible(false);
            btnSaveChanges.setVisible(true);
        }

        refreshMemberSelectionState();
    }

    private void loadComboData() {
        try {
            List<Clan> members = ClientController.getInstance().getAllMembers();
            cmbMember.setModel(new DefaultComboBoxModel<>(members.toArray(new Clan[0])));

            List<Knjiga> books = ClientController.getInstance().getAllBooks();
            cmbBook.setModel(new DefaultComboBoxModel<>(books.toArray(new Knjiga[0])));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Date getDefaultDeadline() {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DAY_OF_MONTH, 14);
        return calendar.getTime();
    }

    private void addItem() {
        try {
            Knjiga knjiga = (Knjiga) cmbBook.getSelectedItem();
            if (knjiga == null) {
                JOptionPane.showMessageDialog(this, "Изабери књигу.");
                return;
            }

            Date deadline = Utility.DATE_FORMAT.parse(txtDeadline.getText().trim());
            Date loanDate = Utility.DATE_FORMAT.parse(txtDate.getText().trim());
            if (deadline.before(loanDate)) {
                throw new ClientValidationException("Рок за враћање не сме бити пре датума изнајмљивања.");
            }
            double finePerDay = parseFinePerDay();

            tableModel.addItem(knjiga);
            StavkaPozajmice item = tableModel.getData().get(tableModel.getData().size() - 1);
            item.setRokZaVracanje(deadline);
            item.setCenaKasnjenja(finePerDay);
            item.azurirajKaznu();
            tableModel.fireTableDataChanged();
            refreshMemberSelectionState();
        } catch (ClientValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Валидација", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Рок за враћање мора бити у формату dd.MM.yyyy", "Валидација", JOptionPane.ERROR_MESSAGE);
        }
    }

    private double parseFinePerDay() throws ClientValidationException {
        try {
            String normalized = txtFinePerDay.getText().trim();
            double value = Double.parseDouble(normalized);
            if (value < 0) {
                throw new ClientValidationException("Цена казне не може бити негативна");
            }
            return value;
        } catch (NumberFormatException ex) {
            throw new ClientValidationException("Цена казне мора бити број");
        }
    }

    private void deleteItem() {
        int row = tblLoanItems.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Изабери ставку из табеле.");
            return;
        }
        tableModel.removeItem(row);
        refreshMemberSelectionState();
    }

    private void createLoanRecord() {
        try {
            commitTableEdit();
            EvidencijaPozajmice record = buildRecordFromForm();
            ClientController.getInstance().createEvidencijaPozajmice(record);
            JOptionPane.showMessageDialog(this, "Систем је запамтио евиденцију позајмице.");
            dispose();
        } catch (ClientValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Валидација", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти евиденцију позајмице.", "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveChanges() {
        try {
            commitTableEdit();
            EvidencijaPozajmice record = buildRecordFromForm();
            record.setEvidencijaPozajmiceID(original.getEvidencijaPozajmiceID());
            record.setState(State.CHANGED);

            ClientController.getInstance().saveEvidencijaPozajmice(record);
            JOptionPane.showMessageDialog(this, "Систем је запамтио евиденцију позајмице.");
            dispose();
        } catch (ClientValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Валидација", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти евиденцију позајмице.", "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private EvidencijaPozajmice buildRecordFromForm() throws ClientValidationException {
        try {
            Date date = Utility.DATE_FORMAT.parse(txtDate.getText().trim());
            Clan member = original != null ? original.getClan() : (Clan) cmbMember.getSelectedItem();
            List<StavkaPozajmice> items = tableModel.getAllForSave();

            if (member == null) {
                throw new ClientValidationException("Члан је обавезан");
            }
            if (items == null || items.isEmpty()) {
                throw new ClientValidationException("Потребна је бар једна ставка евиденције");
            }

            validateItemDatesAgainstLoanDate(date, items);

            int activeCount = 0;
            double totalFine = 0;
            for (StavkaPozajmice item : items) {
                item.azurirajKaznu();
                activeCount++;
                totalFine += item.getIznosKazne();
            }

            EvidencijaPozajmice record = new EvidencijaPozajmice();
            record.setDatumIznajmljivanja(date);
            record.setBibliotekar(logged);
            record.setClan(member);
            record.setBrojStavkiIznajmljivanja(activeCount);
            record.setUkupanIznosKazne(totalFine);
            record.setStavkePozajmice(items);

            for (StavkaPozajmice item : items) {
                item.setEvidencijaPozajmice(record);
            }

            return record;
        } catch (ParseException ex) {
            throw new ClientValidationException("Датум мора бити у формату dd.MM.yyyy");
        }
    }

    private void validateItemDatesAgainstLoanDate(Date loanDate, List<StavkaPozajmice> items) throws ClientValidationException {
        for (StavkaPozajmice item : items) {
            Date deadline = item.getRokZaVracanje();
            if (deadline == null) {
                throw new ClientValidationException("Рок за враћање је обавезан за сваку ставку.");
            }
            if (deadline.before(loanDate)) {
                throw new ClientValidationException("Рок за враћање не сме бити пре датума изнајмљивања.");
            }

            Date returnDate = item.getDatumVracanja();
            if (returnDate != null && returnDate.before(loanDate)) {
                throw new ClientValidationException("Датум враћања не сме бити пре датума изнајмљивања.");
            }
        }
    }

    private void commitTableEdit() {
        if (tblLoanItems.isEditing() && tblLoanItems.getCellEditor() != null) {
            tblLoanItems.getCellEditor().stopCellEditing();
        }
    }

    private void refreshMemberSelectionState() {
        boolean hasItems = !tableModel.getData().isEmpty();
        boolean isEditMode = original != null;
        cmbMember.setEnabled(!isEditMode && !hasItems);
    }
}
