/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogs;

import controller.ClientController;
import domain.Clan;
import domain.Mesto;
import exceptions.ClientValidationException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class ChangeMemberForm extends javax.swing.JDialog {

    private final Clan original;

    /**
     * Creates new form ChangeMemberForm
     */
    public ChangeMemberForm(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public ChangeMemberForm(java.awt.Frame parent, boolean modal, Clan original) {
        super(parent, modal);
        this.original = original;
        initComponents();
        setLocationRelativeTo(parent);
        loadCities();
        initMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbCity = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnCreateMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Име:");

        jLabel2.setText("Презиме:");

        jLabel3.setText("Email:");

        jLabel4.setText("Место:");

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDelete.setText("Обриши");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSaveChanges.setText("Сачувај измене");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnCreateMember.setText("Креирај новог члана");
        btnCreateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(cmbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnCreateMember)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveChanges)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnCreateMember)
                    .addComponent(btnSaveChanges))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMemberActionPerformed
        createMember();
    }//GEN-LAST:event_btnCreateMemberActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteMember();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        saveChanges();
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateMember;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

    private void loadCities() {
        try {
            List<Mesto> cities = ClientController.getInstance().getAllPlaces();
            cmbCity.setModel(new DefaultComboBoxModel<>(cities.toArray(new Mesto[0])));
            if (!cities.isEmpty()) {
                cmbCity.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Систем не може да обрише члана библиотеке",
                    "Грешка",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initMode() {
        boolean editMode = original != null;

        btnDelete.setVisible(editMode);
        btnSaveChanges.setVisible(editMode);
        btnCreateMember.setVisible(!editMode);

        setTitle(editMode ? "Промена члана" : "Креирање члана");

        if (editMode) {
            txtName.setText(original.getIme());
            txtSurname.setText(original.getPrezime());
            txtEmail.setText(original.getEmail());
            cmbCity.setSelectedItem(original.getMesto());
        }
    }

    private void createMember() {
        try {
            Clan clan = buildClanFromForm();
            ClientController.getInstance().createClan(clan);
            JOptionPane.showMessageDialog(this, "Систем је запамтио члана библиотеке.");
            dispose();
        } catch (ClientValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Валидација", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти члана библиотеке",  "Грешка",  JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveChanges() {
        try {
            Clan clan = buildClanFromForm();
            clan.setClanID(original.getClanID());
            ClientController.getInstance().saveClan(clan);
            JOptionPane.showMessageDialog(this, "Систем је запамтио члана библиотеке.");
            dispose();
        } catch (ClientValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Валидација", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,  "Систем не може да запамти члана библиотеке", "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteMember() {
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Потврди брисање?", "Потврда", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }
            ClientController.getInstance().deleteClan(original);
            JOptionPane.showMessageDialog(this, "Систем је обрисао члана библиотеке.");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Clan buildClanFromForm() throws ClientValidationException {
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String email = txtEmail.getText();
        Mesto city = (Mesto) cmbCity.getSelectedItem();

        if (name == null || name.isBlank()) {
            throw new ClientValidationException("Име је обавезно");
        }
        if (surname == null || surname.isBlank()) {
            throw new ClientValidationException("Презиме је обавезно");
        }
        if (email == null || email.isBlank() || !email.contains("@")) {
            throw new ClientValidationException("Имејл није исправан");
        }
        if (city == null) {
            throw new ClientValidationException("Место је обавезно");
        }

        Clan clan = new Clan();
        clan.setIme(name.trim());
        clan.setPrezime(surname.trim());
        clan.setEmail(email.trim());
        clan.setMesto(city);
        return clan;
    }
}
