/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogs;

import controller.ClientController;
import domain.Clan;
import domain.Mesto;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import table.ClanTableModel;

/**
 *
 * @author Korisnik
 */
public class ViewMembersForm extends javax.swing.JDialog {

    private final Frame parentFrame;
    private final ClanTableModel model = new ClanTableModel();

    /**
     * Creates new form ViewMembersForm
     */
    public ViewMembersForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parentFrame = parent;
        initComponents();
        setTitle("Претрага чланова");
        setLocationRelativeTo(parent);
        tblMembers.setModel(model);
        tblMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    openSelected();
                }
            }
        });
        loadPlaces();
        loadAllMembers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMemberCоndition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cmbPlaceCondition = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Име/презиме/шифра члана :");

        btnSearch.setText("Претражи");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMembers);

        jLabel3.setText("Назив места:");

        cmbPlaceCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMemberCоndition, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(cmbPlaceCondition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(41, 41, 41))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMemberCоndition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPlaceCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbPlaceCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTextField txtMemberCоndition;
    // End of variables declaration//GEN-END:variables

    private void search(boolean showSuccessMessage) {
        try {
            List<Object> criteria = new LinkedList<>();
            criteria.add(txtMemberCоndition.getText().trim());
            String selectedPlace = cmbPlaceCondition.getSelectedItem() == null ? "" : cmbPlaceCondition.getSelectedItem().toString();
            criteria.add("Сва места".equals(selectedPlace) ? "" : selectedPlace);

            List<Clan> list = ClientController.getInstance().getMembersByCondition(criteria);
            if (list == null || list.isEmpty()) {
                model.setData(java.util.Collections.emptyList());
                if (showSuccessMessage) {
                    JOptionPane.showMessageDialog(this,"Систем не може да нађе чланове библиотеке по задатим критеријумима.",
                            "Грешка", JOptionPane.ERROR_MESSAGE);
                }
                return;
            }

            model.setData(list);
            if (showSuccessMessage) {
                JOptionPane.showMessageDialog(this, "Систем је нашао чланове библиотеке по задатим критеријумима.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Систем не може да нађе чланове библиотеке по задатим критеријумима. ","Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadPlaces() {
        try {
            List<Mesto> places = ClientController.getInstance().getAllPlaces();
            List<String> placeNames = new LinkedList<>();
            placeNames.add("Сва места");

            for (Mesto mesto : places) {
                placeNames.add(mesto.getNaziv());
            }

            cmbPlaceCondition.setModel(new DefaultComboBoxModel<>(placeNames.toArray(new String[0])));
            cmbPlaceCondition.setSelectedIndex(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Систем не може да учита места.","Грешка",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadAllMembers() {
        try {
            List<Clan> list = ClientController.getInstance().getAllMembers();
            model.setData(list == null ? java.util.Collections.emptyList() : list);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Систем не може да учита чланове библиотеке.",
                    "Грешка",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void openSelected() {
        int row = tblMembers.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Изабери члана из табеле.");
            return;
        }

        Clan selected = model.getAt(row);
        try {
            Clan full = ClientController.getInstance().getMemberByID(selected.getClanID());
            if (full == null) {
                JOptionPane.showMessageDialog(this, "Систем не може да нађе члана библиотеке.", "Грешка", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Систем је нашао члана библиотеке.");
            new ChangeMemberForm(parentFrame, true, full).setVisible(true);
            loadAllMembers();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }
}
