/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogs;

import controller.ClientController;
import domain.Bibliotekar;
import domain.EvidencijaPozajmice;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import table.EvidencijaPozajmiceTableModel;

/**
 *
 * @author Korisnik
 */
public class ViewLoanRecordsForm extends javax.swing.JDialog {

    private final Frame parent;
    private final Bibliotekar logged;
    private final EvidencijaPozajmiceTableModel model = new EvidencijaPozajmiceTableModel();

    /**
     * Creates new form ViewLoanRecordsForm
     */
    public ViewLoanRecordsForm(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public ViewLoanRecordsForm(java.awt.Frame parent, boolean modal, Bibliotekar logged) {
        super(parent, modal);
        this.parent = parent;
        this.logged = logged;
        initComponents();
        setTitle("Претрага евиденција позајмица");
        setLocationRelativeTo(parent);
        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    openSelected();
                }
            }
        });
        search(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        txtAdmin = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRecord = new javax.swing.JTextField();
        txtBook = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Члан:");

        jLabel2.setText("Библиотекар:");

        txtAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminActionPerformed(evt);
            }
        });

        btnSearch.setText("Претражи");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Шифра евиденције:");

        jLabel6.setText("ИСБН књигe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMember, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtAdmin))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBook, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearch)
                                .addGap(36, 36, 36)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(txtAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminActionPerformed
        search(false);
    }//GEN-LAST:event_txtAdminActionPerformed

    private void search(boolean showSuccessMessage) {
        try {
            String evidencijaCondition = txtRecord.getText().trim();
            String clanCondition = txtMember.getText().trim();
            String bibliotekarCondition = txtAdmin.getText().trim();
            String knjigaCondition = txtBook.getText().trim();

            if (!evidencijaCondition.isBlank()) {
                Integer.parseInt(evidencijaCondition);
            }

            List<Object> criteria = new LinkedList<>();
            criteria.add(evidencijaCondition);
            criteria.add(bibliotekarCondition);
            criteria.add(clanCondition);
            criteria.add(knjigaCondition);

            List<EvidencijaPozajmice> list = ClientController.getInstance().getLoanRecordsByCondition(criteria);
            if (list == null || list.isEmpty()) {
                model.setData(list);
                if (showSuccessMessage) {
                    JOptionPane.showMessageDialog(this,"Систем не може да нађе евиденције позајмица по задатим критеријумима.", "Грешка", JOptionPane.ERROR_MESSAGE);
                }
                return;
            }

            model.setData(list);
            if (showSuccessMessage) {
                JOptionPane.showMessageDialog(this, "Систем је нашао евиденције позајмица по задатим критеријумима.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID евиденције мора бити цео број.", "Валидација", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Систем не може да нађе евиденције позајмица по задатим критеријумима.\n" + ex.getMessage(),
                    "Грешка",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void openSelected() {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Изабери евиденцију из табеле.");
            return;
        }

        EvidencijaPozajmice selected = model.getAt(row);
        try {
            EvidencijaPozajmice full = ClientController.getInstance().getLoanRecordByID(selected.getEvidencijaPozajmiceID());
            if (full == null) {
                JOptionPane.showMessageDialog(this, "Систем не може да нађе евиденцију позајмице.", "Грешка", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Систем је нашао евиденцију позајмице.");
            new ChangeLoanRecordForm(parent, true, logged, full).setVisible(true);
            search(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JTextField txtBook;
    private javax.swing.JTextField txtMember;
    private javax.swing.JTextField txtRecord;
    // End of variables declaration//GEN-END:variables
}
