package intercomm;

public enum Operation {
    LOGIN_BIBLIOTEKAR,

    CREATE_EVIDENCIJA_POZAJMICE,
    GET_LOAN_RECORDS_BY_CONDITION,
    GET_LOAN_RECORD_BY_ID,
    SAVE_EVIDENCIJA_POZAJMICE,

    CREATE_CLAN,
    GET_ALL_MEMBERS,
    GET_MEMBERS_BY_CONDITION,
    GET_MEMBER_BY_ID,
    SAVE_CLAN,
    DELETE_CLAN,

    CREATE_SMENA,

    GET_ALL_BOOKS,
    GET_ALL_PLACES,
    GET_ALL_BIBLIOTEKARI
}
